
package com.jkt.kmclindentservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-11-19T16:52:34.117+05:30
 * Generated source version: 3.0.2
 */

@WebFault(name = "BusinessFaultType", targetNamespace = "http://www.jkt.com/entities/indentkmcl")
public class BusinessException extends Exception {
    
    private com.jkt.entities.indentkmcl.BusinessFaultType businessFaultType;

    public BusinessException() {
        super();
    }
    
    public BusinessException(String message) {
        super(message);
    }
    
    public BusinessException(String message, Throwable cause) {
        super(message, cause);
    }

    public BusinessException(String message, com.jkt.entities.indentkmcl.BusinessFaultType businessFaultType) {
        super(message);
        this.businessFaultType = businessFaultType;
    }

    public BusinessException(String message, com.jkt.entities.indentkmcl.BusinessFaultType businessFaultType, Throwable cause) {
        super(message, cause);
        this.businessFaultType = businessFaultType;
    }

    public com.jkt.entities.indentkmcl.BusinessFaultType getFaultInfo() {
        return this.businessFaultType;
    }
}
