package com.jkt.kmclindentservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-11-19T16:52:34.125+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://www.jkt.com/KmclIndentService/", name = "IKmclIndentService")
@XmlSeeAlso({com.jkt.entities.indentkmcl.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IKmclIndentService {

    @WebResult(name = "IndentListResponseType", targetNamespace = "http://www.jkt.com/entities/indentkmcl", partName = "parameters")
    @WebMethod(action = "http://www.jkt.com/KmclIndentService/getAllIndent")
    public com.jkt.entities.indentkmcl.IndentListResponseType getAllIndent(
        @WebParam(partName = "parameters", name = "IndentListRequestType", targetNamespace = "http://www.jkt.com/entities/indentkmcl")
        com.jkt.entities.indentkmcl.IndentListRequestType parameters
    ) throws BusinessException;
}
