package com.jkt.services.indentservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-10-26T18:33:14.040+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://www.jkt.com/services/IndentService/", name = "IIndentService")
@XmlSeeAlso({com.jkt.entities.indent.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IIndentService {

    @WebResult(name = "IndentListResponseType", targetNamespace = "http://www.jkt.com/entities/indent", partName = "parameters")
    @WebMethod
    public com.jkt.entities.indent.IndentListResponseType getAllItemOfindent(
        @WebParam(partName = "parameters", name = "IndentListRequestType", targetNamespace = "http://www.jkt.com/entities/indent")
        com.jkt.entities.indent.IndentListRequestType parameters
    ) throws BusinessException;
}
