//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 03:19:01 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.uidai.gov.in/authentication/uid-bfd-request/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package in.gov.uidai.authentication.uid_bfd_request._1;
