<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:tns="http://www.jkt.com/services/IndentService/"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="IndentService"
   xmlns:indentx="http://www.jkt.com/entities/indent"
 targetNamespace="http://www.jkt.com/services/IndentService/">
  <wsdl:types>
        <xsd:schema targetNamespace="http://www.jkt.com/services/IndentService/">
            <xsd:import namespace="http://www.jkt.com/entities/indent"
                schemaLocation="../entities/indent.xsd" />
        </xsd:schema>
    </wsdl:types>
 
    <wsdl:message name="IndentListRequest">
        <wsdl:part element="indentx:IndentListRequestType" name="parameters" />
    </wsdl:message>
    <wsdl:message name="IndentListResponse">
        <wsdl:part element="indentx:IndentListResponseType" name="parameters" />
    </wsdl:message>
    <wsdl:message name="BusinessException">
        <wsdl:part element="indentx:BusinessFaultType" name="parameters" />
    </wsdl:message>
 
    <wsdl:portType name="IIndentService">
        <wsdl:operation name="getAllItemOfindent">
            <wsdl:input message="tns:IndentListRequest" />
            <wsdl:output message="tns:IndentListResponse" />
            <wsdl:fault name="businessException" message="tns:BusinessException" />
        </wsdl:operation>
    </wsdl:portType>
 
    <wsdl:binding name="IndentServiceSOAPBinding" type="tns:IIndentService">
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="getAllItemOfindent">
            <soap:operation
                soapAction="http://www.jkt.com/services/IndentService/getAllItemOfindent" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
            <wsdl:fault name="businessException">
                <soap:fault name="businessException" use="literal" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
 
    <wsdl:service name="IndentService">
        <wsdl:port name="IndentService" binding="tns:IndentServiceSOAPBinding">
            <soap:address
                location="http://localhost:8080/hms/services/indent/IndentService" />
        </wsdl:port>
    </wsdl:service>
 
</wsdl:definitions>