//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 03:19:01 PM IST 
// Modified on:2014.12.19


package in.gov.uidai.authentication.uid_auth_request._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import in.gov.uidai.authentication.common.types._1.*;
import in.gov.uidai.kyc.uid_kyc_request._1.Kyc;


/**
 * <p>Java class for Auth complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Auth">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tkn" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}Tkn" minOccurs="0"/>
 *         &lt;element name="Uses" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}Uses"/>
 *         &lt;element name="Meta" type="{http://www.uidai.gov.in/authentication/common/types/1.0}Meta"/>
 *         &lt;element name="Skey" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}Skey"/>
 *         &lt;element name="Data">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
 *                 &lt;attribute name="type" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}DataType" default="X" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Hmac" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uid" use="required" type="{http://www.uidai.gov.in/authentication/common/types/1.0}uid" />
 *       &lt;attribute name="ac" use="required" type="{http://www.uidai.gov.in/authentication/common/types/1.0}AuaCode" />
 *       &lt;attribute name="tid" use="required" type="{http://www.uidai.gov.in/authentication/common/types/1.0}Tid" />
 *       &lt;attribute name="ver" type="{http://www.uidai.gov.in/authentication/common/types/1.0}Ver" />
 *       &lt;attribute name="txn" use="required" type="{http://www.uidai.gov.in/authentication/common/types/1.0}Txn" />
 *       &lt;attribute name="lk" use="required" type="{http://www.uidai.gov.in/authentication/common/types/1.0}LicenseKey" />
 *       &lt;attribute name="sa" use="required" type="{http://www.uidai.gov.in/authentication/common/types/1.0}AuaCode" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Auth", propOrder = {
	"txn",
	"ver",
	"RC",
    "subAUACode",
    "reqType",
    "deviceId",    
    "uid",
    "Other",
    "token",
    "meta",
    "uses",
    "skey",
    "data",
    "hmac",
    "kyc"
})
public class Auth {
	@XmlElement(name = "Txn")
    protected Txn txn;
	@XmlElement(name = "Ver")
    protected Ver ver;
	@XmlElement(name = "SubAUACode")
    protected SubAUACode subAUACode;
	@XmlElement(name = "ReqType")
    protected ReqType reqType;
    @XmlElement(name = "DeviceId")
    protected DeviceId deviceId;
    @XmlElement(name = "UID")
    protected UID uid;
    @XmlElement(name = "Uses", required = true)
    protected Uses uses;
    @XmlElement(name = "Meta", required = true)
    protected Meta meta;
    @XmlElement(name = "Skey", required = true)
    protected Skey skey;
    @XmlElement(name = "Data", required = true)
    protected Auth.Data data;
    @XmlElement(name = "Hmac", required = true)
    protected byte[] hmac;
    @XmlElement(name = "Kyc", required = true)
    protected Kyc kyc;
    @XmlElement(name = "RC")
    protected Rc RC;
    @XmlElement(name = "Other")
    protected Other Other;
    @XmlElement(name = "token")
    protected Token token;

    public Kyc getKyc() {
		return kyc;
	}

	public void setKyc(Kyc kyc) {
		this.kyc = kyc;
	}

	public SubAUACode getSubAUACode() {
		return subAUACode;
	}

	public void setSubAUACode(SubAUACode subAUACode) {
		this.subAUACode = subAUACode;
	}

	public ReqType getReqType() {
		return reqType;
	}

	public void setReqType(ReqType reqType) {
		this.reqType = reqType;
	}

	public DeviceId getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(DeviceId deviceId) {
		this.deviceId = deviceId;
	}

	/**
     * Gets the value of the uses property.
     * 
     * @return
     *     possible object is
     *     {@link Uses }
     *     
     */
    public Uses getUses() {
        return uses;
    }

    /**
     * Sets the value of the uses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uses }
     *     
     */
    public void setUses(Uses value) {
        this.uses = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * @return
     *     possible object is
     *     {@link Meta }
     *     
     */
    public Meta getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta }
     *     
     */
    public void setMeta(Meta value) {
        this.meta = value;
    }

    /**
     * Gets the value of the skey property.
     * 
     * @return
     *     possible object is
     *     {@link Skey }
     *     
     */
    public Skey getSkey() {
        return skey;
    }

    /**
     * Sets the value of the skey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Skey }
     *     
     */
    public void setSkey(Skey value) {
        this.skey = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Auth.Data }
     *     
     */
    public Auth.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Auth.Data }
     *     
     */
    public void setData(Auth.Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the hmac property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getHmac() {
        return hmac;
    }

    /**
     * Sets the value of the hmac property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setHmac(byte[] value) {
        this.hmac = ((byte[]) value);
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public UID getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(UID uid) {
        this.uid = uid;
    }

    
    /**
     * Gets the value of the ver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Ver getVer() {
        return ver;
    }

    /**
     * Sets the value of the ver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVer(Ver ver) {
        this.ver = ver;
    }

    /**
     * Gets the value of the txn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Txn getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxn(Txn txn) {
        this.txn = txn;
    }

    public Rc getRC() {
		return RC;
	}

	public void setRC(Rc rC) {
		RC = rC;
	}

	public Other getOther() {
		return Other;
	}

	public void setOther(Other other) {
		Other = other;
	}

	public Token getToken() {
		return token;
	}

	public void setToken(Token token) {
		this.token = token;
	}




	/**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
     *       &lt;attribute name="type" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}DataType" default="X" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Data {

        @XmlValue
        protected byte[] value;
        @XmlAttribute
        protected DataType type;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setValue(byte[] value) {
            this.value = ((byte[]) value);
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link DataType }
         *     
         */
        public DataType getType() {
            if (type == null) {
                return DataType.X;
            } else {
                return type;
            }
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType }
         *     
         */
        public void setType(DataType value) {
            this.type = value;
        }

    }

}
